project:
  type: website
  output-dir: docs

website:
  title: "Predicting The President"
  navbar:
    left:
      - href: index.qmd
        text: Scientific Paper
      - common.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    crossref:
      fig-title: '**Figure**'
      fig-labels: arabic
      title-delim: "**.**"
