project:
  type: website
  output-dir: docs

website:
  title: "Predicting The President"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - common.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
